---
title: "Rembrant"
author: "TF"
output: 
  bookdown::html_document2:
    toc: yes
    toc_float: true
    number_sections: FALSE
    fig_caption: TRUE
    table_caption: TRUE
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r setup, results='hide'}

library(dplyr)
library(ggplot2)
library(survival)

lapply(list.files(path = here::here("functions"), full.names = TRUE), source)

df_rembrandt <- fct_load_clean_rembrandt()

```

# Describe Rembrandt cohort

```{r desc}
##### Description
df_rembrandt |> 
  dplyr::select(AGE_RANGE,
                GENDER,
                EVENT_OS,
                OVERALL_SURVIVAL_MONTHS,
                DISEASE_TYPE) |> 
  gtsummary::tbl_summary(by = DISEASE_TYPE)
```

```{r genecount, fig.cap="Rembrandt count per patient per tumor type"}
df_rembrandt |> 
  dplyr::select(-c(AGE_RANGE,
                   GENDER,
                   EVENT_OS,
                   OVERALL_SURVIVAL_MONTHS)) |> 
  tidyr::pivot_longer(cols = -c(BIOSPECIMEN_ID, DISEASE_TYPE)) |> 
  ggplot(mapping = aes(x = BIOSPECIMEN_ID, y = value, fill = DISEASE_TYPE)) +
  geom_boxplot(outlier.shape = NA,lwd=0.1, alpha=1) +
  facet_wrap(.~DISEASE_TYPE, scales = "free_x") +
  theme_minimal() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = "none")+
  labs(x = "patients",
       y = "counts")

```

```{r rembrandtpca, fig.cap="First two PCA factorial plans"}
pca_model <- df_rembrandt |> 
  dplyr::select(-c(BIOSPECIMEN_ID,
                   DISEASE_TYPE,
                   AGE_RANGE,
                   GENDER,
                   EVENT_OS,
                   OVERALL_SURVIVAL_MONTHS)) |> 
  FactoMineR::PCA(ncp = 4, graph = FALSE)

pca_coord <- pca_model$ind$coord |> 
  as.data.frame() |> 
  mutate(BIOSPECIMEN_ID = df_rembrandt$BIOSPECIMEN_ID,
         DISEASE_TYPE = df_rembrandt$DISEASE_TYPE,
         .before = 1)

p1 <- plot(pca_model, choix = "ind", axes = c(1, 2))
p2 <- plot(pca_model, choix = "ind", axes = c(3, 4))

ggpubr::ggarrange(p1, p2, common.legend = TRUE)
```

Here are the kaplan meier curves for the two types of disease: 

```{r kmrembrandt, fig.cap="Kaplan meier curves for Astro, Oligo"}
fit <- survfit(Surv(time=OVERALL_SURVIVAL_MONTHS, event=EVENT_OS) ~ DISEASE_TYPE,
               data = df_rembrandt)


p_type=survminer::ggsurvplot(fit,
                             data = df_rembrandt,
                             surv.median.line = "hv", # Add medians survival
                             
                             palette = c("#8338EC", "#FFB703"),
                             
                             # Change legends: title & labels
                             legend.title = "Type",
                             legend.labs = c("Astrocytoma", "Oligodendroglioma"),
                             
                             conf.int = TRUE,
                             # Add risk table
                             risk.table = TRUE,
                             tables.height = 0.2,
                             tables.theme = survminer::theme_cleantable(),
                             
                             title="Type of disease",
                             ggtheme = theme_bw() # Change ggplot2 theme
)
p_type

```

# Rembrandt pathway analysis

```{r importrembrandtpathway}
df_rembrandt_pathway <- lapply(list.files(here::here("results/rembrandt/"), full.names = T),
                               readRDS) |> 
  bind_rows() |> 
  select(-starts_with("time_"), -nb_genes) |> 
  tidyr::pivot_longer(cols = c("sGBJ", "GBT", "Wald", "GT"),
                      names_to = "method",
                      values_to = "p_value") |> 
  group_by(grade, method) |> 
  mutate(p_value_BH = p.adjust(p_value)) |> 
  ungroup() |> 
  mutate(significant = as.integer(p_value_BH < 0.05))
```


```{r upsetplot, fig.cap="Upset plot of the different methods", fig.height=8}
ls_plots <- df_rembrandt_pathway |> 
  filter(significant == 1) |>
  group_by(pathway, grade) |> 
  summarise(methods = list(unique(method))) |> 
  group_by(grade) |> 
  group_split() |> 
  lapply(FUN = function(df_i){
    title_i <- unique(df_i$grade)
    plot_i <- df_i |> 
      ggplot(aes(x=methods)) +
      geom_bar() +
      ggupset::scale_x_upset(n_intersections = 6, order_by = "freq") +
      theme_minimal() +
      ggtitle(title_i)
    
    return(plot_i)
  })
ggpubr::ggarrange(plotlist = ls_plots, ncol = 1)
```

```{r}
nb_pathway = df_rembrandt_pathway |> 
  pull(pathway) |> 
  unique() |> 
  length()

df_sGBJ_rank <- df_rembrandt_pathway |> 
  group_by(grade) |> 
  filter(method == "sGBJ") |> 
  mutate(sGBJ_rank = rank(p_value)) |> 
  ungroup() |> 
  select(pathway, grade, sGBJ_rank)

df_BH_limit <- data.frame(sGBJ_rank = seq(1:nb_pathway)) |> 
  mutate(p_value = 0.05/nb_pathway * sGBJ_rank)

df_rembrandt_pathway |> 
  left_join(df_sGBJ_rank, by = c("pathway", "grade")) |> 
  ggplot(mapping = aes(x = sGBJ_rank, y = p_value)) +
  geom_hline(mapping = aes(color = "5% threshold", yintercept = 0.05)) +
  geom_line(data = df_BH_limit, mapping = aes(color = "BH limit")) +
  ggnewscale::new_scale_color() +
  geom_point(mapping = aes(color = method)) +
  facet_grid(grade ~ ., scales = "free_y") +
  scale_y_log10() +
  annotation_logticks(sides = "l") +
  theme_minimal()
```

