---
title: "VarCovar Rembrandt"
author: "TF"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
dfdata <- readRDS("data/rembrandt/dfresvarcovar.rds")
```

Each dot in the following figure corresponds to one pathway.

# Variance

Each dot in the figure corresponds to the mean and the variance of a pathway. In the draft, variance of the gene expression was set to 0.2.

```{r}
dfdata %>%
  filter(param == "var") %>%
  ggplot(mapping = aes(x = mean,
                       y = var,
                       color = signif)) +
  geom_point() +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(x = "Mean of variance", y = "Variance of variance",
       title = "Rembrandt variance distribution of genes of a given pathway",
       color = "Significant",
       subtitle = "Paper : variance = 0.2")
```

# Covariance

Each dot in the figure corresponds to the mean and the variance of the covariance of a pathway. In the draft, we used three scenario represented above.

```{r}
data_paper <- data.frame(mean = c(0, 0.4*0),
                         var = c(0, 0.4^2*0.01^2))

dfdata %>%
  filter(param == "covar") %>%
  ggplot(mapping = aes(x = mean,
                       y = var,
                       color = signif)) +
  geom_point() +
  geom_point(data_paper, mapping = aes(color = "Draft"), size = 5) +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_y_log10() +
  labs(x = "Mean", y = "Variance", color = "",
       title = "Rembrandt covariance distribution",
       subtitle = "Draft scenario II is not shown (mean = 0.4*0.4, var = 0.1^2*0.4^2)")
```





